Algoritmo "Para"

Var
   AleatorioMaximo, AleatorioMinimo, incremento : inteiro

Inicio

   repita
      aleatorio 1,100
      leia(AleatorioMaximo)
      leia(AleatorioMinimo)

      aleatorio off
   ate AleatorioMaximo >= AleatorioMinimo
   limpatela

   aleatorio 1,5
   leia(incremento)
   aleatorio off
   limpatela
   para i de AleatorioMinimo ate AleatorioMaximo passo incremento faca

Fimalgoritmo
