Algoritmo "Trabalhando com tipos de variáveis"

Var

   palavra1, palavra2, palavra3 : caractere
   numero1, numero2, numero3: inteiro


Inicio
   Escreval ("Palavra 1:")
   Leia(palavra1)
   Escreval ("Palavra 2:")
   Leia(palavra2)
   Escreval ("Numero 1:")
   Leia(numero1)
   Escreval ("Numero 2:")
   leia(numero2)
   palavra3 <- palavra1 + palavra2
   numero3  <- numero1  + numero2
   EscrevaL(palavra3)
   EscrevaL(numero3)
fimalgoritmo









Fimalgoritmo