/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ex24;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(((Object) classUnderTest).getGreeting(), "app should have a greeting");
    }
}
